import { useEffect, useMemo, useRef, useState } from 'react'
import { AlertCircle, BookOpen, Check, ChevronDown, ChevronRight, Circle, Clock3, FileImage, FlaskConical, History, Image, Lightbulb, LoaderCircle, Menu, MessageSquare, Paperclip, Pencil, Plus, RefreshCw, RotateCcw, Send, Settings, ShieldCheck, Sparkles, Trash2, Upload, X } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import remarkMath from 'remark-math'
import rehypeKatex from 'rehype-katex'
import { api } from './api.js'
import { analysisRunKey, analysisStage, bindConversationResize, clampConversationHeight, groupKnowledge, knowledgeState, questionProgress, savedConversationHeight, shouldResumeAnalysis } from './domain.js'

const TASK_LABELS = { vision: '图片理解与局部复核', solve: '独立解题与诊断', chat: '解释与自由追问', generate: '变式生成', verify: '变式复核' }
const PURPOSES = { variant: '最小变式', prerequisite: '验证基础', depth: '深入测试', verify: '验证一下' }
const PROCESSING = new Set(['recognizing', 'extracted', 'analyzing', 'training', 'chatting'])
const IMAGE_TYPES = 'image/png,image/jpeg,image/webp'
const answerText = value => Array.isArray(value) ? value.join(',') : String(value ?? '')
const defaults = () => [{ id: crypto.randomUUID(), name: '图片模型', base_url: 'https://api.openai.com/v1', model: '', api_key: '', has_key: false }, { id: crypto.randomUUID(), name: '主模型', base_url: 'https://api.openai.com/v1', model: '', api_key: '', has_key: false }]

function Markdown({ children }) { return <ReactMarkdown remarkPlugins={[remarkGfm, remarkMath]} rehypePlugins={[rehypeKatex]}>{children || ''}</ReactMarkdown> }
function Modal({ title, onClose, children, wide }) { return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className={`modal ${wide ? 'wide' : ''}`} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="icon-button" onClick={onClose}><X size={18}/></button></header>{children}</section></div> }

function Sidebar({ open, sessions, currentId, onSelect, onCreate, onDemo, onKnowledge, onSettings, onDelete }) {
  return <aside className={`sidebar ${open ? 'mobile-open' : ''}`}><div className="brand"><span className="brand-mark"><Sparkles size={15}/></span><strong>电网学习助手</strong></div><button className="new-session" onClick={onCreate}><Plus size={17}/>新建学习</button><div className="session-title">最近学习</div><nav className="session-list">{!sessions.length && <p className="muted small">还没有学习记录</p>}{sessions.map(s => <div className={`session-row ${s.id === currentId ? 'active' : ''}`} key={s.id}><button onClick={() => onSelect(s.id)}><MessageSquare size={15}/><span>{s.title || '未命名学习'}</span>{PROCESSING.has(s.status) && <LoaderCircle className="spin" size={13}/>}{s.demo && <em>演示</em>}</button><button className="session-delete" onClick={() => onDelete(s)}><Trash2 size={13}/></button></div>)}</nav><div className="sidebar-footer"><button onClick={onDemo}><FlaskConical size={17}/>打开演示</button><button onClick={onKnowledge}><BookOpen size={17}/>知识状态</button><button onClick={onSettings}><Settings size={17}/>模型设置</button></div></aside>
}

function Welcome({ busy, onFiles, onDemo }) { const input = useRef(); return <div className="welcome"><span className="welcome-icon"><Sparkles size={25}/></span><h1>上传做过的题，看看哪里值得停一下</h1><p>先独立解题，再把整页结果压缩成知识点和需要关注的地方。</p><button className="upload-card" onClick={() => input.current?.click()} disabled={busy}><Upload size={21}/><span><strong>上传题目图片</strong><small>PNG、JPEG 或 WebP，支持多张</small></span></button><input ref={input} hidden type="file" accept={IMAGE_TYPES} multiple onChange={e => e.target.files.length && onFiles(e.target.files)}/><button className="text-button" onClick={onDemo}><FlaskConical size={16}/>查看明确标注的演示</button><div className="privacy-note"><ShieldCheck size={15}/>学习记录与密钥保存在本机</div></div> }
function StatusPill({ question }) { const a = question.analysis; if (!a) return <span className="pill neutral"><Circle size={12}/>待分析</span>; if (a.status === 'pending') return <span className="pill warning"><Clock3 size={12}/>待确认</span>; return a.correct ? <span className="pill success"><Check size={12}/>正确</span> : <span className="pill danger"><X size={12}/>需订正</span> }

function AttachmentStrip({ session, busy, onDelete }) { if (!session.attachments?.length) return null; return <div className="attachments">{session.attachments.map(a => <div className={`attachment-chip ${a.deleted ? 'deleted' : ''}`} key={a.id}>{a.url ? <a href={a.url} target="_blank" rel="noreferrer"><FileImage size={14}/>{a.name}</a> : <span><FileImage size={14}/>{a.name}（原图已清理）</span>}{a.url && <button disabled={busy} onClick={() => onDelete(a.id)}><X size={12}/></button>}</div>)}</div> }

function Overview({ session, selectedId, onSelect, onTrain, onDeleteAttachment, busy }) {
  const stats = questionProgress(session.questions), analyzed = session.questions.filter(q => q.analysis), recognized = session.questions.filter(q => !q.analysis), stage = analysisStage(session.status)
  const passed = analyzed.filter(q => q.analysis.status === 'confirmed' && q.analysis.correct === true && q.analysis.reasoning_ok !== false && !['unsure', 'guess'].includes(q.confidence))
  const attention = analyzed.filter(q => !passed.includes(q)), uncertain = analyzed.filter(q => ['unsure', 'guess'].includes(q.confidence)).length
  return <>{session.demo && <div className="demo-banner"><FlaskConical size={16}/><span><strong>演示数据</strong>　预置内容，仅用于体验界面，不是实时模型结果。</span></div>}<section className="workspace-header"><div><span className="eyebrow">整页学习概览</span><h1>{session.title || '本次学习'}</h1></div><div className="progress-copy"><strong>{stats.confirmed}/{stats.total}</strong><span>已可靠判断</span></div></section>{session.error && <div className="error-banner"><AlertCircle size={16}/><span>{session.error}</span></div>}<AttachmentStrip session={session} busy={busy} onDelete={onDeleteAttachment}/><section className="summary-strip"><div><span>本页题目</span><strong>{stats.total}</strong></div><div><span>确认正确</span><strong>{stats.correct}</strong></div><div><span>需关注</span><strong>{attention.filter(q => q.analysis.status !== 'pending').length}</strong></div><div><span>待确认</span><strong>{stats.pending}</strong></div>{uncertain > 0 && <small>其中 {uncertain} 题作答时有犹豫或猜测</small>}</section>
    {passed.length > 0 && <section className="result-section"><header><div><span className="section-kicker success">直接通过</span><h2>一句话知识点</h2></div><span>{passed.length} 题</span></header><div className="pass-list">{passed.map(q => <button key={q.id} className={selectedId === q.id ? 'selected' : ''} onClick={() => onSelect(q.id)}><span className="mini-number">{q.number || '—'}</span><Check size={14}/><strong>{q.analysis.knowledge_point || q.knowledge || '本题关键知识'}</strong><ChevronRight size={14}/></button>)}</div></section>}
    {attention.length > 0 && <section className="result-section attention-section"><header><div><span className="section-kicker warning">需要关注</span><h2>错误、犹豫与待确认</h2></div><span>{attention.length} 题</span></header><div className="attention-list">{attention.map(q => <article key={q.id} className={selectedId === q.id ? 'selected' : ''} onClick={() => onSelect(q.id)}><div className="attention-head"><span className="mini-number">{q.number || '—'}</span><StatusPill question={q}/><span className="taxonomy">{q.knowledge || q.chapter || '待归类'}</span></div><h3>{q.analysis.knowledge_point || q.text}</h3><p>{q.analysis.diagnosis || q.analysis.hint}</p>{q.analysis.distinction && <div className="inline-distinction"><strong>关键区分</strong><span>{q.analysis.distinction}</span></div>}<footer><button className="link-button" onClick={e => { e.stopPropagation(); onSelect(q.id) }}>查看原题与作答<ChevronRight size={14}/></button><button className="secondary compact" disabled={busy} onClick={e => { e.stopPropagation(); onTrain({ question_id: q.id, purpose: 'variant' }) }}><RotateCcw size={13}/>练一道变式</button></footer></article>)}</div></section>}
    {recognized.length > 0 && <section className="result-section"><header><div><span className="section-kicker">已识别</span><h2>题目与作答</h2></div><span>{recognized.length} 题</span></header><div className="attention-list">{recognized.map(q => <article key={q.id} className={selectedId === q.id ? 'selected' : ''} onClick={() => onSelect(q.id)}><div className="attention-head"><span className="mini-number">{q.number || '—'}</span><StatusPill question={q}/><span className="taxonomy">{q.knowledge || q.chapter || '待归类'}</span></div><h3>{q.text}</h3><p>{answerText(q.user_answer) ? `你的作答：${answerText(q.user_answer)}` : '未识别到明确作答'}</p><footer><button className="link-button" onClick={e => { e.stopPropagation(); onSelect(q.id) }}>核对题目与作答<ChevronRight size={14}/></button></footer></article>)}</div></section>}
    {!analyzed.length && <div className="empty-panel"><LoaderCircle className={stage.active ? 'spin' : ''} size={23}/><strong>{stage.active ? stage.title : '这页还没有分析结果'}</strong><p>{stage.active ? stage.detail : '已上传内容会保留，可以直接重试。'}</p></div>}</>
}

function AnswerEditor({ draft, setDraft }) {
  const values = answerText(draft.user_answer).split(/[、,，\s]+/).filter(Boolean)
  const toggle = key => setDraft(d => { if (d.kind !== 'multiple') return { ...d, user_answer: key }; const current = answerText(d.user_answer).split(/[、,，\s]+/).filter(Boolean); return { ...d, user_answer: current.includes(key) ? current.filter(x => x !== key).join(',') : [...current, key].join(',') } })
  if (draft.options?.length) return <div className="option-editor"><span className="field-label">选项与我的答案</span>{draft.options.map((o, i) => <div className="option-row" key={o.key}><button className={values.includes(o.key) ? 'chosen' : ''} onClick={() => toggle(o.key)}>{o.key}</button><input value={o.text || ''} onChange={e => setDraft(d => ({ ...d, options: d.options.map((x, n) => n === i ? { ...x, text: e.target.value } : x) }))}/></div>)}</div>
  return <label>我的答案<input value={answerText(draft.user_answer)} placeholder={draft.kind === 'judge' ? '例如：正确 / 错误' : '输入简短答案'} onChange={e => setDraft({ ...draft, user_answer: e.target.value })}/></label>
}

function QuestionPanel({ session, question, busy, onClose, onSave, onAnalyze, onReveal, onRetry, onRecheck, onTrain }) {
  const [draft, setDraft] = useState(question), [reference, setReference] = useState(''), [retry, setRetry] = useState(''), [retryReasoning, setRetryReasoning] = useState(''), [showAnalysis, setShowAnalysis] = useState(false)
  useEffect(() => { setDraft(question); setRetry(''); setRetryReasoning(''); setShowAnalysis(false) }, [question])
  const source = session.attachments?.find(a => a.id === question.attachment_id)
  return <aside className="inspector"><header className="inspector-header"><div><span>原题与作答</span><strong>第 {question.number || '—'} 题</strong></div><button className="icon-button" onClick={onClose}><X size={18}/></button></header><div className="inspector-body">{source?.url ? <a className="source-image" href={source.url} target="_blank" rel="noreferrer"><img src={source.url} alt="原始题目页面"/><span><Image size={14}/>打开原图</span></a> : source?.deleted && <div className="image-missing">原图已清理，识别内容仍保留。</div>}{question.recognition_note && <div className="recognition-note"><AlertCircle size={14}/>{question.recognition_note}</div>}<label>题干<textarea value={draft.text || ''} onChange={e => setDraft({ ...draft, text: e.target.value })}/></label><label>题型<select value={draft.kind || 'single'} onChange={e => setDraft({ ...draft, kind: e.target.value, user_answer: '' })}><option value="single">单选题</option><option value="multiple">多选题</option><option value="judge">判断题</option></select></label><AnswerEditor draft={draft} setDraft={setDraft}/><label>我的思路<textarea className="short" value={draft.reasoning || ''} placeholder="公式、关键步骤或判断依据（可选）" onChange={e => setDraft({ ...draft, reasoning: e.target.value })}/></label><label>把握程度<select value={draft.confidence || 'unknown'} onChange={e => setDraft({ ...draft, confidence: e.target.value })}><option value="certain">确定</option><option value="unsure">不确定</option><option value="guess">猜测</option><option value="unknown">未标注</option></select></label><button className="secondary full" disabled={busy} onClick={() => onSave({ text: draft.text, options: draft.options, user_answer: answerText(draft.user_answer), reasoning: draft.reasoning || '', confidence: draft.confidence, kind: draft.kind })}><Pencil size={15}/>保存识别修改</button>{!question.analysis && <button className="primary full" disabled={busy} onClick={onAnalyze}><Sparkles size={15}/>分析整页</button>}
    {question.analysis && <section className={`analysis-box ${question.analysis.status === 'pending' ? 'pending' : question.analysis.correct ? 'correct' : 'incorrect'}`}><header><StatusPill question={question}/><small>{question.analysis.source || ''}</small></header><h3>{question.analysis.knowledge_point}</h3><Markdown>{question.analysis.diagnosis}</Markdown>{question.analysis.distinction && <div className="distinction"><strong>关键区分</strong><Markdown>{question.analysis.distinction}</Markdown></div>}{question.analysis.hint && <div className="hint"><Lightbulb size={15}/><Markdown>{question.analysis.hint}</Markdown></div>}<button className="fold-button" onClick={() => setShowAnalysis(!showAnalysis)}>{showAnalysis ? <ChevronDown size={15}/> : <ChevronRight size={15}/>}详细解析</button>{showAnalysis && (question.revealed || question.analysis.explanation ? <div className="explanation"><div className="answer-line"><span>参考答案</span><strong>{answerText(question.analysis.answer) || '—'}</strong></div><Markdown>{question.analysis.explanation}</Markdown></div> : <button className="secondary full" disabled={busy} onClick={onReveal}>揭示答案与解析</button>)}</section>}
    {question.analysis && <><div className="retry-box"><strong>修改后重答</strong><input value={retry} placeholder="新的答案" onChange={e => setRetry(e.target.value)}/><textarea value={retryReasoning} placeholder="新的判断依据（可选）" onChange={e => setRetryReasoning(e.target.value)}/><button className="primary full" disabled={busy || !retry.trim()} onClick={async () => { if (await onRetry(retry, retryReasoning)) { setRetry(''); setRetryReasoning('') } }}>提交重答</button></div><div className="section-label">继续练习</div><div className="training-actions">{Object.entries(PURPOSES).map(([purpose, label]) => <button key={purpose} disabled={busy} onClick={() => onTrain({ question_id: question.id, purpose })}>{label}</button>)}</div><label>补充参考或申请复核<textarea className="short" value={reference} placeholder="教材原文、标准答案或异议" onChange={e => setReference(e.target.value)}/></label><button className="secondary full" disabled={busy || !reference.trim()} onClick={async () => { if (await onRecheck(reference)) setReference('') }}><RefreshCw size={15}/>按参考内容复核</button></>}</div></aside>
}

function QuizCard({ message, sessionId, busy, onUpdate, run }) {
  const quiz = message.quiz, [answer, setAnswer] = useState(''), [reasoning, setReasoning] = useState(''), [reference, setReference] = useState(''), [open, setOpen] = useState(false)
  if (!quiz) return null
  const options = quiz.question?.options || [], toggle = key => setAnswer(prev => { const v = prev.split(',').filter(Boolean); return v.includes(key) ? v.filter(x => x !== key).join(',') : [...v, key].join(',') })
  return <div className="quiz-card"><div className="quiz-meta"><Sparkles size={15}/>{PURPOSES[quiz.purpose] || '专项练习'}</div><Markdown>{quiz.question?.text}</Markdown>{options.map(o => <label className="quiz-option" key={o.key}><input checked={answer.split(',').includes(o.key)} type={quiz.question.kind === 'multiple' ? 'checkbox' : 'radio'} name={quiz.id} disabled={quiz.status === 'answered'} onChange={() => quiz.question.kind === 'multiple' ? toggle(o.key) : setAnswer(o.key)}/><span>{o.key}. {o.text}</span></label>)}{!options.length && quiz.status !== 'answered' && <input className="quiz-short-answer" value={answer} placeholder={quiz.question?.kind === 'judge' ? '输入“正确”或“错误”' : '输入你的答案'} onChange={e => setAnswer(e.target.value)}/>} {quiz.status === 'answered' ? <div className={`quiz-feedback ${quiz.correct ? 'correct' : 'incorrect'}`}><strong>{quiz.correct ? '本次回答正确' : '这次还需要检查'}</strong><Markdown>{quiz.feedback}</Markdown><button className="fold-button" onClick={() => setOpen(!open)}>{open ? <ChevronDown size={15}/> : <ChevronRight size={15}/>}答案与解析</button>{open && (quiz.revealed || quiz.answer || quiz.explanation ? <div className="explanation"><div className="answer-line"><span>参考答案</span><strong>{answerText(quiz.correct_answer || quiz.answer) || '—'}</strong></div><Markdown>{quiz.explanation}</Markdown></div> : <button className="secondary" disabled={busy} onClick={() => run(() => api.revealQuiz(sessionId, quiz.id), onUpdate)}>揭示答案</button>)}<div className="quiz-recheck"><input value={reference} placeholder="补充依据后复核" onChange={e => setReference(e.target.value)}/><button disabled={busy || !reference.trim()} onClick={async () => { if (await run(() => api.recheckQuiz(sessionId, quiz.id, reference), onUpdate)) setReference('') }}>复核</button></div></div> : <><textarea value={reasoning} placeholder="可选：写下判断依据" onChange={e => setReasoning(e.target.value)}/><button className="primary" disabled={busy || !answer.trim()} onClick={async () => { if (await run(() => api.answerQuiz(sessionId, quiz.id, { answer, reasoning }), onUpdate)) { setAnswer(''); setReasoning('') } }}>提交答案</button></>}</div>
}

function Conversation({ session, selectedId, busy, run, onUpdate }) {
  const [text, setText] = useState(''), [reference, setReference] = useState(''), referenceInput = useRef()
  const [height, setHeight] = useState(() => {
    if (typeof window === 'undefined') return savedConversationHeight(null, 900)
    try { return savedConversationHeight(window.localStorage, window.innerHeight) } catch { return savedConversationHeight(null, window.innerHeight) }
  })
  const resizeStart = useRef(null)
  useEffect(() => bindConversationResize(window, setHeight), [])
  const send = async () => { if (text.trim() && await run(() => api.message(session.id, { text, question_id: selectedId || session.selected_question_id || undefined }), onUpdate)) setText('') }
  const saveHeight = next => { const value = clampConversationHeight(next, window.innerHeight); setHeight(value); try { window.localStorage.setItem('grid-learning.conversation-height', String(value)) } catch {} return value }
  const startResize = event => { event.preventDefault(); resizeStart.current = { y: event.clientY, height }; const move = next => setHeight(clampConversationHeight(resizeStart.current.height + resizeStart.current.y - next.clientY, window.innerHeight)); const finish = next => { if (next) saveHeight(resizeStart.current.height + resizeStart.current.y - next.clientY); else saveHeight(height); window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', finish); window.removeEventListener('pointercancel', finish); resizeStart.current = null }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', finish); window.addEventListener('pointercancel', finish) }
  const adjustHeight = delta => saveHeight(height + delta)
  return <section className="conversation" style={{ '--conversation-height': `${height}px` }}><header><h2>继续学习</h2>{selectedId && <span>当前：第 {session.questions.find(q => q.id === selectedId)?.number || '—'} 题</span>}</header><div className="conversation-resizer" role="separator" aria-orientation="horizontal" aria-label="调整对话区高度" aria-valuemin="156" aria-valuemax={clampConversationHeight(Number.MAX_SAFE_INTEGER, window.innerHeight)} aria-valuenow={height} tabIndex="0" onPointerDown={startResize} onKeyDown={e => { if (e.key === 'ArrowUp') { e.preventDefault(); adjustHeight(16) } if (e.key === 'ArrowDown') { e.preventDefault(); adjustHeight(-16) } }}/>{!session.messages?.length && <p className="muted">可以追问任意题，也可以直接说“解释第 5 题”。</p>}<div className="messages">{session.messages?.map(m => <div key={m.id} className={`message ${m.role}`}><div className="message-role">{m.role === 'user' ? '你' : m.role === 'assistant' ? '学习助手' : '系统'}</div>{m.type === 'quiz' ? <QuizCard message={m} sessionId={session.id} busy={busy} onUpdate={onUpdate} run={run}/> : <Markdown>{m.content}</Markdown>}</div>)}</div><div className="reference-tools"><div className="reference-row"><input value={reference} placeholder="添加文字参考" onChange={e => setReference(e.target.value)}/><button disabled={!reference.trim() || busy} onClick={async () => { if (await run(() => api.reference(session.id, reference), onUpdate)) setReference('') }}>添加</button></div><button className="secondary" disabled={busy} onClick={() => referenceInput.current?.click()}><Image size={15}/>添加参考截图</button><input ref={referenceInput} hidden type="file" accept={IMAGE_TYPES} multiple onChange={e => e.target.files.length && run(() => api.referenceUpload(session.id, e.target.files), onUpdate)}/></div><div className="chat-composer"><textarea value={text} rows="2" placeholder={session.mode === 'hint' ? '继续追问，我会先给提示…' : '继续追问这次学习…'} onChange={e => setText(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send() } }}/><button className="send-button" disabled={busy || !text.trim()} onClick={send}><Send size={17}/></button></div></section>
}

function SettingsModal({ initial, busy, onClose, onSaved, run }) {
  const profiles = initial?.profiles?.length ? initial.profiles : defaults(), [advanced, setAdvanced] = useState(false)
  const [value, setValue] = useState({ ...initial, profiles, tasks: initial?.profiles?.length ? initial.tasks : { vision: profiles[0].id, solve: profiles[1].id, chat: profiles[1].id, generate: profiles[1].id, verify: profiles[1].id }, mode: initial?.mode || 'direct' })
  const add = () => setValue(v => ({ ...v, profiles: [...v.profiles, { id: crypto.randomUUID(), name: '新模型', base_url: 'https://api.openai.com/v1', model: '', api_key: '', has_key: false }] })), profile = (i, patch) => setValue(v => ({ ...v, profiles: v.profiles.map((p, n) => n === i ? { ...p, ...patch } : p) }))
  return <Modal title="模型与学习设置" onClose={onClose} wide><div className="modal-body"><div className="setting-section"><div className="setting-heading"><div><h3>模型配置</h3><p>默认准备图片模型与主模型两个位置。密钥明文不会返回网页。</p></div><button className="secondary" onClick={add}><Plus size={15}/>添加</button></div>{value.profiles.map((p, i) => <div className="profile-card" key={p.id}><div className="profile-grid"><label>名称<input value={p.name} onChange={e => profile(i, { name: e.target.value })}/></label><label>接口地址<input value={p.base_url} onChange={e => profile(i, { base_url: e.target.value })}/></label><label>模型名称<input value={p.model} onChange={e => profile(i, { model: e.target.value })}/></label><label>并发上限<input type="number" min="1" max="8" step="1" value={p.parallel ?? ''} placeholder="沿用全局" onChange={e => profile(i, { parallel: e.target.value ? Number(e.target.value) : null })}/></label><label>API Key<input type="password" value={p.api_key || ''} placeholder={p.has_key ? '已保存，留空则保留' : '输入密钥'} onChange={e => profile(i, { api_key: e.target.value })}/></label></div><div className="profile-actions"><label className="thinking-toggle"><input type="checkbox" checked={!!p.disable_thinking} onChange={e => profile(i, { disable_thinking: e.target.checked })}/><span>关闭深度思考</span></label><button className="text-button" disabled={busy || !p.model} onClick={() => run(() => api.testProfile(p.id), result => window.alert(result.message))}>测试连接</button>{p.has_key && <button className="text-button danger-text" onClick={() => profile(i, { remove_key: true, api_key: '', has_key: false })}>移除密钥</button>}<button className="text-button danger-text" onClick={() => setValue(v => ({ ...v, profiles: v.profiles.filter((_, n) => n !== i) }))}>删除</button></div></div>)}</div><div className="setting-section"><button className="advanced-toggle" onClick={() => setAdvanced(!advanced)}>{advanced ? <ChevronDown size={16}/> : <ChevronRight size={16}/>}高级任务覆盖</button>{advanced && <div className="task-map">{Object.entries(TASK_LABELS).map(([key, label]) => <label key={key}><span>{label}</span><select value={value.tasks[key] || ''} onChange={e => setValue(v => ({ ...v, tasks: { ...v.tasks, [key]: e.target.value } }))}><option value="">未配置</option>{value.profiles.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>)}</div>}</div><div className="setting-section"><h3>默认回答方式</h3><div className="segmented"><button className={value.mode === 'direct' ? 'active' : ''} onClick={() => setValue({ ...value, mode: 'direct' })}>直接讲解</button><button className={value.mode === 'hint' ? 'active' : ''} onClick={() => setValue({ ...value, mode: 'hint' })}>先给提示</button></div></div></div><footer className="modal-footer"><button className="secondary" onClick={onClose}>取消</button><button className="primary" disabled={busy} onClick={() => run(() => api.saveSettings(value), onSaved)}>保存设置</button></footer></Modal>
}

function KnowledgeModal({ rows, onClose, onVerify, busy }) { const groups = groupKnowledge(rows), [expanded, setExpanded] = useState(null); return <Modal title="知识状态" onClose={onClose} wide><div className="modal-body knowledge-body"><p className="knowledge-intro">这里只显示作答形成的证据和可解释判断；单题答对不会直接认定掌握。</p>{!groups.length && <div className="empty-panel"><BookOpen size={24}/><p>完成真实作答分析后，这里会逐步形成记录。</p></div>}{groups.map(g => <section className="knowledge-group" key={g.subject}><h3>{g.subject}</h3>{g.chapters.map(c => <div key={c.chapter}><div className="chapter-title">{c.chapter}</div>{c.items.map(item => <article className="knowledge-row" key={item.id}><button className="knowledge-main" onClick={() => setExpanded(expanded === item.id ? null : item.id)}><span className={`state-dot ${knowledgeState(item.state).key}`}/><span><strong>{item.name}</strong><small>{item.summary || '暂无总结'}</small></span><span className={`state-label ${knowledgeState(item.state).key}`}>{knowledgeState(item.state).label}</span>{expanded === item.id ? <ChevronDown size={16}/> : <ChevronRight size={16}/>}</button>{expanded === item.id && <div className="evidence-panel"><div className="evidence-head"><span><History size={14}/>证据 {item.evidence_count || item.evidence?.length || 0} 条</span><button className="secondary" disabled={busy} onClick={() => onVerify(item.id)}>验证一下</button></div>{item.evidence?.map((e, i) => <div className="evidence-item" key={e.id || i}><span>{e.correct === false ? '需订正' : '作答记录'}</span><p>{e.summary || e.description || e.question || '学习证据'}</p><time>{e.created_at || ''}</time></div>)}</div>}</article>)}</div>)}</section>)}</div></Modal> }
function DeleteModal({ session, onClose, onConfirm, busy }) { const [all, setAll] = useState(false); return <Modal title="删除学习记录" onClose={onClose}><div className="modal-body"><p>将删除“{session.title || '未命名学习'}”及其对话和原图。</p><label className="danger-choice"><input type="checkbox" checked={all} onChange={e => setAll(e.target.checked)}/><span><strong>同时删除学习证据</strong><small>勾选后会撤回这次学习形成的证据，并按剩余记录重新计算。</small></span></label></div><footer className="modal-footer"><button className="secondary" onClick={onClose}>取消</button><button className="danger-button" disabled={busy} onClick={() => onConfirm(all)}>确认删除</button></footer></Modal> }

export default function App() {
  const [sessions, setSessions] = useState([]), [session, setSession] = useState(null), [selectedId, setSelectedId] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [sidebar, setSidebar] = useState(false), [settings, setSettings] = useState(null), [knowledge, setKnowledge] = useState(null), [deleting, setDeleting] = useState(null)
  const fileInput = useRef(), autoStarted = useRef(new Set()), resumeKey = analysisRunKey(session), selected = useMemo(() => session?.questions?.find(q => q.id === selectedId), [session, selectedId]), refreshSessions = async () => { const rows = await api.sessions(); setSessions(rows); return rows }
  useEffect(() => { refreshSessions().catch(e => setError(e.message)) }, [])
  useEffect(() => { if (!sessions.some(s => PROCESSING.has(s.status))) return; const timer = setInterval(async () => { try { const rows = await refreshSessions(); const row = session && rows.find(s => s.id === session.id); if (row && row.status !== session.status) setSession(await api.session(session.id)) } catch {} }, 1800); return () => clearInterval(timer) }, [sessions, session])
  useEffect(() => { if (session?.selected_question_id && session.selected_question_id !== selectedId) setSelectedId(session.selected_question_id) }, [session?.selected_question_id])
  const run = async (action, success) => { setBusy(true); setError(''); try { const result = await action(); success?.(result); return result } catch (e) { setError(e.message); return null } finally { setBusy(false) } }, update = d => { setSession(d); refreshSessions().catch(() => {}) }, choose = id => run(() => api.session(id), d => { update(d); setSelectedId(d.selected_question_id || null); setSidebar(false) }), create = () => run(() => api.createSession({ title: '新的学习' }), d => { update(d); setSelectedId(null); setSidebar(false) }), demo = () => run(api.demo, d => { update(d); setSelectedId(null); setSidebar(false) })
  useEffect(() => { if (!session || busy || !shouldResumeAnalysis(session.status) || autoStarted.current.has(resumeKey)) return; autoStarted.current.add(resumeKey); const timer = window.setTimeout(() => { run(() => api.analyze(session.id), update) }, 0); return () => window.clearTimeout(timer) }, [session?.status, resumeKey, busy])
  const files = async list => { let current = session; if (!current || current.demo) current = await run(() => api.createSession({ title: '图片学习' }), update); if (current) await run(async () => { const uploaded = await api.upload(current.id, list); update(uploaded); return api.extractStream(current.id, question => setSession(previous => previous?.id === current.id ? { ...previous, status: 'recognizing', error: null, questions: [...previous.questions, question] } : previous)) }, d => { update(d); setSelectedId(null) }) }
  return <div className="app-shell"><Sidebar open={sidebar} sessions={sessions} currentId={session?.id} onSelect={choose} onCreate={create} onDemo={demo} onKnowledge={() => run(api.knowledge, setKnowledge)} onSettings={() => run(api.settings, setSettings)} onDelete={setDeleting}/><main className={`main ${selected ? 'with-inspector' : ''}`}><header className="topbar"><button className="icon-button mobile-menu" onClick={() => setSidebar(!sidebar)}><Menu size={19}/></button><div className="topbar-title">{session?.title || '学习工作台'}</div><div className="topbar-actions">{session && <div className="segmented compact"><button className={session.mode === 'direct' ? 'active' : ''} disabled={busy} onClick={() => run(() => api.patchSession(session.id, { mode: 'direct' }), update)}>直接</button><button className={session.mode === 'hint' ? 'active' : ''} disabled={busy} onClick={() => run(() => api.patchSession(session.id, { mode: 'hint' }), update)}>提示</button></div>}<button className="icon-button" onClick={() => run(api.settings, setSettings)}><Settings size={18}/></button></div></header>{error && <div className="global-error"><AlertCircle size={16}/><span>{error}</span><button onClick={() => setError('')}><X size={15}/></button></div>}{busy && <div className="busy-bar"><LoaderCircle size={15} className="spin"/>正在处理，请稍候</div>}<div className="content">{!session ? <Welcome busy={busy} onFiles={files} onDemo={demo}/> : <div className="session-content">{session.questions?.length ? <div className="overview-pane"><Overview session={session} selectedId={selectedId} onSelect={setSelectedId} busy={busy} onTrain={body => run(() => api.train(session.id, body), update)} onDeleteAttachment={aid => run(() => api.deleteAttachment(session.id, aid), update)}/></div> : <div className="session-empty"><Welcome busy={busy} onFiles={files} onDemo={demo}/>{session.attachments?.length > 0 && <button className="primary" disabled={busy} onClick={() => run(() => api.analyze(session.id), update)}><RefreshCw size={16}/>重试分析</button>}</div>}{!!session.questions?.length && <Conversation session={session} selectedId={selectedId} busy={busy} run={run} onUpdate={update}/>}</div>}</div><input ref={fileInput} hidden type="file" accept={IMAGE_TYPES} multiple onChange={e => e.target.files.length && files(e.target.files)}/>{session && <button className="floating-upload" onClick={() => fileInput.current?.click()}><Paperclip size={18}/></button>}</main>
    {session && selected && <QuestionPanel session={session} question={selected} busy={busy} onClose={() => setSelectedId(null)} onSave={draft => run(() => api.patchQuestion(session.id, selected.id, draft), update)} onAnalyze={() => run(() => api.analyze(session.id), update)} onReveal={() => run(() => api.reveal(session.id, selected.id), update)} onRetry={(answer, reasoning) => run(() => api.retryQuestion(session.id, selected.id, { answer, reasoning }), update)} onRecheck={text => run(() => api.recheck(session.id, selected.id, text), update)} onTrain={body => run(() => api.train(session.id, body), update)}/>} {settings && <SettingsModal initial={settings} busy={busy} onClose={() => setSettings(null)} run={run} onSaved={result => { setSettings(null); if (session && result.mode !== session.mode) run(() => api.patchSession(session.id, { mode: result.mode }), update) }}/>} {knowledge && <KnowledgeModal rows={knowledge} busy={busy} onClose={() => setKnowledge(null)} onVerify={knowledge_id => session && run(() => api.train(session.id, { knowledge_id, purpose: 'verify' }), d => { update(d); setKnowledge(null) })}/>} {deleting && <DeleteModal session={deleting} busy={busy} onClose={() => setDeleting(null)} onConfirm={all => run(() => api.deleteSession(deleting.id, all), () => { if (session?.id === deleting.id) { setSession(null); setSelectedId(null) } setDeleting(null); refreshSessions() })}/>}</div>
}
